
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Player column actions
export const REQUEST_ALIVE_PLAYERS ='REQUEST_ALIVE_PLAYERS';
export const RECEIVE_ALIVE_PLAYERS ='RECEIVE_ALIVE_PLAYERS';
